# Generated by Django 3.2.15 on 2022-09-13 01:18

import django.db.models.deletion
from django.db import migrations, models

from apps.recipes.models import MealTime, RecipeType


def add_meal_times(apps, schema_editor):
    meal_time_model = apps.get_model("recipes.MealTime")
    for key, val in MealTime.Choices.choices:
        meal_time_model.objects.create(name=val)


def add_recipe_types(apps, schema_editor):
    recipe_type_model = apps.get_model("recipes.RecipeType")
    for key, val in RecipeType.Choices.choices:
        recipe_type_model.objects.create(name=val)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MealTime",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RecipeType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("ingredients", models.TextField(blank=True, null=True)),
                ("meal_times", models.ManyToManyField(blank=True, to="recipes.MealTime")),
                (
                    "recipe_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="recipes.recipetype"
                    ),
                ),
            ],
        ),
        migrations.RunPython(add_meal_times, migrations.RunPython.noop),
        migrations.RunPython(add_recipe_types, migrations.RunPython.noop),
    ]
