# Generated by Django 3.2.15 on 2022-09-16 13:01

from django.db import migrations

import apps.base.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealtime",
            name="name",
            field=apps.base.model_fields.PlainCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=apps.base.model_fields.PlainTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=apps.base.model_fields.PlainTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=apps.base.model_fields.PlainCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="recipetype",
            name="name",
            field=apps.base.model_fields.PlainCharField(max_length=100),
        ),
    ]
