# Generated by Django 3.2.15 on 2022-10-10 20:00
from django.db import migrations, models

import apps.base.model_fields
from apps.recipes.models import DietType


def add_diet_types(apps, schema_editor):
    diet_types_model = apps.get_model("recipes.DietType")
    for key, value in DietType.Choices.choices:
        diet_types_model.objects.create(name=value)


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_switch_to_plain_text_and_plain_char_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", apps.base.model_fields.PlainCharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_diet_friendly",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="diet_types",
            field=models.ManyToManyField(blank=True, to="recipes.DietType"),
        ),
        migrations.RunPython(add_diet_types, migrations.RunPython.noop),
    ]
